from .test_search_product import SearchProductTest
from .test_sort_product import SortProductTest
from .test_filter_product import FilterProductTest
from .test_product_detail import ProductDetailTest
from .test_update_product import UpdateProductTest
from .test_cancel_order import CancelOrderTest
from .test_add_credit_card import AddCreditCardTest
from .test_comment_rating import CommentRatingTest
from .test_update_status import UpdateStatusTest
from .test_create_chat import CreateChatTestCase
from .test_google_login import GoogleLoginTestCase
from .test_register import RegistrationTestCase
from .test_register_activate import RegistrationActivateTestCase
from .test_send_message import SendMessageFailTestCase
from .test_recommend_product import RecommendProductTest
