name: CI_backend_in_master

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "app/backend/**"
    branches:
      - backend
  pull_request:
    branches:
      - backend
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # Runs a set of commands using the runners shell
      - name: docker build
        run: |
          docker build ./app/backend -t django_app --build-arg KEY=${{ secrets.SECRET_KEY_C }}
          echo build is completed.

      - name: docker tag
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag django_app $DOCKER_USER/django_app
          echo tag is completed.
      - name: docker push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker push $DOCKER_USER/django_app
          echo push is completed.

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 18.195.107.160
          username: ec2-user
          key: ${{ secrets.OMG_SECRET }}
          port: 22

          script: |
            cd bounswe2020group5/
            git pull
            bash .github/workflows/backend_script.sh
